In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
sumo=pd.read_csv('winequality-red.csv')
sumo.head(n=10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5

In [4]:
col=['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol','quality']
sumo=pd.read_csv('winequality-red.csv',names=col,header=1)
sumo.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
1,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
2,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
3,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
4,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5

In [5]:
sumo.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1593,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1594,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1595,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1596,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1597,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [6]:
sumo.count()

fixed acidity           1598
volatile acidity        1598
citric acid             1598
residual sugar          1598
chlorides               1598
free sulfur dioxide     1598
total sulfur dioxide    1598
density                 1598
pH                      1598
sulphates               1598
alcohol                 1598
quality                 1598
dtype: int64

In [7]:
range=[]
for i in sumo['quality']:
    if i>=3 and i<=5 :
        range.append('1')
    elif i>5 and i<=8 :
        range.append('2')
sumo['Range']=range

In [8]:
sumo.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Range
0,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
1,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,1
2,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,2
3,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,1
4,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,1

In [9]:
sumo.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1598.000000,1598.000000,1598.000000,1598.000000,1598.000000,1598.000000,1598.000000,1598.000000,1598.000000,1598.000000,1598.000000,1598.000000
mean,8.320213,0.527713,0.271145,2.539205,0.087474,15.877972,46.475594,0.996746,3.310989,0.658210,10.423623,5.636421
std,1.741489,0.179064,0.194744,1.410279,0.047079,10.462720,32.904142,0.001888,0.154355,0.169542,1.065694,0.807665
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997837,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [10]:
X=sumo.iloc[:,0:11]
y=sumo.iloc[:,-1]

In [11]:
bestfeatures = SelectKBest(score_func=chi2,k=10)
fit = bestfeatures.fit(X,y)
dfscores=pd.DataFrame(fit.scores_)
dfcolumns=pd.DataFrame(X.columns)
featureScores=pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']
print(featureScores.nlargest(10,'Score'))

                   Specs        Score
6   total sulfur dioxide  2007.806227
5    free sulfur dioxide    42.454805
10               alcohol    32.832780
1       volatile acidity     9.998713
2            citric acid     5.600941
0          fixed acidity     5.229478
9              sulphates     3.307876
4              chlorides     0.486956
3         residual sugar     0.007604
7                density     0.000144

In [12]:
feature=['fixed acidity','citric acid','chlorides','total sulfur dioxide','density','pH','sulphates','alcohol', 'quality']

In [13]:
X = sumo[feature]
Y = sumo.Range

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=0)

In [16]:
log_reg = LogisticRegression()
log_reg.fit(X_train,Y_train)

LogisticRegression()

In [17]:
Y_pred=log_reg.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
accuracy_score(Y_test,Y_pred)

1.0

In [20]:
Y_test.value_counts()

2    218
1    182
Name: Range, dtype: int64

In [21]:
Y_test.mean()

inf

In [22]:
print("True quality :    "),Y_test.values[0:15]

True quality :

(None,
 array(['2', '1', '2', '2', '2', '2', '2', '2', '1', '2', '2', '1', '2',
        '1', '2'], dtype=object))

In [23]:
print("Predicted quality :   "),Y_pred[0:15]

Predicted quality :

(None,
 array(['2', '1', '2', '2', '2', '2', '2', '2', '1', '2', '2', '1', '2',
        '1', '2'], dtype=object))

In [24]:
from sklearn.metrics import confusion_matrix,recall_score

In [25]:
confusion_matrix(Y_test,Y_pred)

array([[182,   0],
       [  0, 218]], dtype=int64)